In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv('synthetic_cases.csv')

In [3]:
dataset

,case_id,amount_due,days_overdue,past_defaults,credit_score,dca_success_rate,contact_attempts,recovered
0,C1,16795,176,1,368,0.625513,5,1
1,C2,1860,358,3,601,0.410045,8,1
2,C3,77820,253,1,452,0.746749,1,1
3,C4,55886,246,1,836,0.841640,7,1
4,C5,7265,227,1,334,0.888430,3,1
...,...,...,...,...,...,...,...,...
9995,C9996,16438,252,2,794,0.877906,8,1
9996,C9997,89921,358,2,559,0.750252,5,1
9997,C9998,45999,180,0,784,0.461741,2,0
9998,C9999,19482,349,1,612,0.598610,2,1
9999,C10000,33471,110,0,401,0.857684,5,1

In [4]:
dataset.columns

Index(['case_id', 'amount_due', 'days_overdue', 'past_defaults',
       'credit_score', 'dca_success_rate', 'contact_attempts', 'recovered'],
      dtype='object')

In [11]:
independent=dataset[['amount_due', 'days_overdue', 'past_defaults',
       'credit_score', 'dca_success_rate', 'contact_attempts']]

In [12]:
dependent=dataset[['recovered']]

In [13]:
from sklearn.model_selection import train_test_split as tts
x_train,x_test,y_train,y_test=tts(independent,dependent,test_size=1/3,random_state=0)

In [14]:
y_test

      recovered
9394          1
898           0
2398          1
5906          1
2343          0
...         ...
5032          1
8898          1
2038          1
7184          0
2095          1

[3334 rows x 1 columns]

In [15]:
from sklearn.linear_model import LogisticRegression
reg=LogisticRegression(random_state=0)
reg.fit(x_train,y_train)

C:\Users\USER\anaconda3\envs\ml\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\USER\anaconda3\envs\ml\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(random_state=0)

In [16]:
y_pred=reg.predict(x_test)

In [17]:
from sklearn.metrics import roc_auc_score
auc = roc_auc_score(y_test, y_pred)

In [18]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,y_pred)

In [23]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.53      0.31      0.39      1387
           1       0.62      0.80      0.70      1947

    accuracy                           0.60      3334
   macro avg       0.57      0.56      0.54      3334
weighted avg       0.58      0.60      0.57      3334

In [25]:
# Save model
import joblib
joblib.dump(reg, "recovery_model.pkl")

print("Model trained and saved successfully!")

Model trained and saved successfully!